create table person
(
    id        int generated by default as identity primary key,
    name      varchar(32)        not null,
    lastname  varchar(32)        not null,
    address   varchar(128)       not null,
    phone     varchar unique     not null,
    email     varchar(64) unique not null,
    username  varchar(32) unique not null,
    password  varchar            not null,
    role      varchar            not null,
    is_enable boolean            not null
);
drop table person;

create table category
(
    id   int generated by default as identity primary key,
    name varchar unique not null
);

create table product
(
    id          int generated by default as identity primary key,
    title       varchar                                              not null,
    price       decimal(8, 2) check ( price > 0 and price <= 100000) not null,
    article     varchar unique                                       not null,
    count_left  int check ( count_left >= 0 )                        not null,
    description text,
    category_id int references category (id)
);
drop table product;

create table product_photo
(
    id         int generated by default as identity primary key,
    name       varchar        not null,
    url        varchar unique not null,
    product_id int            not null references product (id) on delete cascade,
    is_primary boolean        not null
);
drop table product_photo;

create table orders
(
    id               int generated by default as identity primary key,
    person_id        int references person (id)                            not null,
    status           varchar                                               not null,
    created_at       timestamp without time zone default current_timestamp not null,
    delivery_address varchar                                               not null,
    comment          varchar
);
drop table orders;

create table cart_item
(
    id         int generated by default as identity primary key,
    person_id  int                         not null references person (id) on delete cascade,
    product_id int                         not null references product (id) on delete cascade,
    quantity   int check ( quantity >= 0 ) not null,
    order_id   int                         references orders (id) on delete set null
);
drop table cart_item;

create table comment
(
    person_id  int references person (id) on delete cascade  not null,
    product_id int references product (id) on delete cascade not null,
    primary key (person_id, product_id),
    comment    varchar                                       not null
);
drop table comment;

create table activation
(
    id    int generated by default as identity primary key,
    key   varchar unique not null,
    email varchar        not null
);
drop table activation;

delete from product where category_id is null;
delete from product where category_id = 1;
delete from product where id =10;



