create table if not exists person
(
    id        int generated by default as identity primary key,
    name      varchar(32)        not null,
    lastname  varchar(32)        not null,
    address   varchar(128)       not null,
    phone     varchar unique     not null,
    email     varchar(64) unique not null,
    username  varchar(32) unique not null,
    password  varchar            not null,
    role      varchar            not null,
    is_enable boolean            not null
);
-- drop table person;
-- insert into person (name, lastname, address, phone, email, username, password, role, is_enable)
-- values ('Anonymous', 'User', '00000, Unknown, Anonymous Street', '+0000000000',
--         'anonymous@example.com', 'guest', '', 'GUEST', true);
alter table person add column created_at timestamp without time zone default current_timestamp;



create table if not exists category
(
    id   int generated by default as identity primary key,
    name varchar unique not null
);

create table if not exists product
(
    id           int generated by default as identity primary key,
    title        varchar                                              not null,
    price        decimal(8, 2) check ( price > 0 and price <= 100000) not null,
    article      varchar unique                                       not null,
    count_left   int check ( count_left >= 0 )                        not null,
    description  text,
    category_id  int references category (id),
    sale_price   decimal(8, 2) check ( sale_price > 0 and sale_price <= price),
    date_expired timestamp without time zone
);
-- drop table product;
-- alter table product
--     add column sale_price decimal(8, 2) check ( sale_price > 0 and sale_price <= price);
-- alter table product
--     add column date_expired timestamp without time zone;

create table if not exists product_photo
(
    id         int generated by default as identity primary key,
    name       varchar        not null,
    url        varchar unique not null,
    product_id int            not null references product (id) on delete cascade,
    is_primary boolean        not null
);
-- drop table product_photo;

create table if not exists orders
(
    id               int generated by default as identity primary key,
    person_id        int references person (id)                            not null,
    status           varchar                                               not null,
    created_at       timestamp without time zone default current_timestamp not null,
    delivery_address varchar                                               not null,
    comment          varchar,
    name             varchar                                               not null,
    lastname         varchar                                               not null,
    phone            varchar                                               not null
);
-- drop table orders;

create table if not exists cart_item
(
    id         int generated by default as identity primary key,
    person_id  int                         not null references person (id) on delete cascade,
    product_id int                         not null references product (id) on delete cascade,
    quantity   int check ( quantity >= 0 ) not null,
    order_id   int                         references orders (id) on delete set null
);
-- drop table cart_item;

create table if not exists comment
(
    person_id  int references person (id) on delete cascade          not null,
    product_id int references product (id) on delete cascade         not null,
    primary key (person_id, product_id),
    comment    varchar                                               not null,
    created_at timestamp without time zone default current_timestamp not null
);
-- drop table comment;

create table if not exists activation
(
    id    int generated by default as identity primary key,
    key   varchar unique not null,
    email varchar        not null references person (email) on delete cascade
);
drop table activation;

create table if not exists wishlist
(
    id         int generated by default as identity unique,
    person_id  int not null references person (id) on delete cascade,
    product_id int not null references product (id) on delete cascade,
    primary key (person_id, product_id)
);
-- drop table wishlist;

-- delete
-- from product
-- where category_id is null;
-- delete
-- from product
-- where category_id = 1;
-- delete
-- from product
-- where id < 24;
-- select *
-- from product;
-- delete
-- from category
-- where id >= 2
--   AND id <= 7;

create table if not exists telegram_user
(
    id       int generated by default as identity primary key,
    chat_id  bigint unique not null,
    username varchar,
    phone    varchar,
    name     varchar,
    lastname varchar
);

create table if not exists order_phone_call
(
    id        int generated by default as identity primary key,
    chat_id   bigint,
    phone     varchar,
    date      timestamp without time zone default current_timestamp,
    username  varchar,
    name      varchar,
    lastname  varchar,
    is_called boolean
);
-- drop table order_phone_call;

-- select *
-- from product
-- where id = 25
--    or id = 34;


create table if not exists telegram_correspondence
(
    id       int generated by default as identity primary key,
    chat_id  bigint not null,
    is_admin boolean,
    message  text   not null,
    date     timestamp without time zone default current_timestamp
);
-- drop table telegram_correspondence;

create table if not exists promo_code
(
    id              int generated by default as identity primary key,
    code            varchar(16) unique          not null,
    discount        double precision            not null,
    expiration_date timestamp without time zone not null,
    is_percentage   boolean                     not null,
    category_id     int references category(id) on delete cascade
);
-- alter table promo_code
--     add column category_id int;
